Card layout | Ml/feature/card item
PL-FE-SEP23-REACTivation/product-catalog pull request #3
Opened 2024-02-07 18:59 UTC by MarcinLigmann

[CLICK UP TASK LINK](https://app.clickup.com/t/8693qv7cb)

2024-02-07 21:49 UTC, zaura333 requested changes

2024-02-07 21:49 UTC, zaura333 commented on src/components/Footer/ProductCard/ProductCard.tsx
> +        <ButtonFavorite>heart</ButtonFavorite>
Might be good to keep product info as an object and then pass it as a prop to product card, later it'll be easier to then get rid of hardcoded part to data from api. You could use one from src/public/api/phones.json

2024-02-07 21:49 UTC, zaura333 commented on src/components/Footer/ProductCard/ProductCard.css
> +}
Couldn't this class also be written as a styled component?

2024-02-08 14:40 UTC, szymanski-marcin approved these changes

2024-02-08 14:50 UTC, zaura333 approved these changes

2024-02-08 15:14 UTC, merged