added reg page layout + reg routes + icon on header
PL-FE-SEP23-REACTivation/product-catalog pull request #62
Opened 2024-02-20 15:05 UTC by bertsu02

2024-02-20 17:02 UTC, zaura333 requested changes

2024-02-20 17:02 UTC, zaura333 commented on src/utils/mixins.scss
> +  @media (min-width: 640px) and (max-width: 1199px) {
```suggestion
  @media (min-width: 640px) {
```

Not neccessary for mobile first styling

2024-02-21 10:50 UTC, zaura333 approved these changes

2024-02-21 13:17 UTC, MarcinLigmann approved these changes

2024-02-21 14:29 UTC, merged